force-app/main/default/objects/Lead/fields/Got_Answer__c.field-meta.xml
<CustomField>
    <fullName>Got_Answer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Got Answer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Have_Budget__c.field-meta.xml
<CustomField>
    <fullName>Have_Budget__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Have Budget</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadScore__c.field-meta.xml
<CustomField>
    <fullName>LeadScore__c</fullName>
    <label>LeadScore</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadScoreHandler.cls
public class LeadScoreHandler {
    public static void calculateLeadScore(List<Lead> leads) {
        for (Lead lead : leads) {
            Integer leadScore = 0;

            if (lead.Industry == 'Electronics' || lead.Industry == 'Energy' || lead.Industry == 'Consulting'
                || lead.Industry == 'Communications' || lead.Industry == 'Biotechnology') {
                leadScore += 10;
            } else if (lead.Industry == null) {
                leadScore += 0;
            } else{
                LeadScore += 5;
            }


            if (lead.Status == 'Working - Contacted' || lead.Status == 'Closed - Converted') {
                leadScore += 10;     
            } else {
                leadScore += 0;
            }

            
            if (lead.Rating == 'Cold') {
                leadScore += 2;
            } else if (lead.Rating == 'Warm') {
                leadScore += 5;
            } else if (lead.Rating == 'Hot') {
                leadScore += 10;
            }

            if (lead.AnnualRevenue >= 100000) {
                leadScore += 10;
            } else if (lead.AnnualRevenue == 0){
                leadScore += 0;
            }else{
                leadScore += 8;
            }

            if (lead.Have_Budget__c == true) {
                leadScore += 10;
            } else {
                leadScore += 0;
            }


            if (lead.Got_Answer__c == true) {
                leadScore += 5;
            } else {
                leadScore += 0;
            }


            lead.LeadScore__c = leadScore;
        }
    }
}